# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.1

    branches:
      only:
        - develop

    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: deps-{{ checksum "project.clj" }}
      - run: lein test
      - run: lein deploy clojars
